#███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗ 
#██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
#███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
#╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝ 
#███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║     
#╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝     
                                                            
format = """
[╭──](blue)\
[](blue)\
[.](blue)\
$time\
[.](blue)\
$directory\
$cmd_duration\
$all\
$line_break\
[╰─](blue)\
$character\
"""

[username]
format = "[$user](bold red)"
show_always = false

[hostname]
format = "[$hostname](bold red)"
ssh_only = false
disabled = true

[directory]
format = "[\\[](blue)[$path](bold cyan)[\\]](blue)"
truncation_length = 3
truncate_to_repo = false

[time]
format = "[\\(](blue)[$time]( #F5E0DC)[\\)](blue)"
time_format ="%d.%b.%Y|%I.%M %p" 
disabled = false

[cmd_duration]
format = '[\[$duration\]]($style)'
style = "bold blue"
min_time = 1000

[character]
success_symbol = "[ ❯]( #89dceb)"
error_symbol = "[x❯](bold red)"

[python]
format = '\[[󰌠 $version (\($virtualenv\))]($style)\]'
style = 'bold #eaff64'

[rust]
format = '\[[󱘗 $version]($style)\]'
style = 'bold teal'

[git_branch]
format = ' \[[$symbol$branch]($style) '
symbol = ' '
style = 'bold purple'

[git_status]
format = '[$all_status$ahead_behind]($style)\]'
style = 'bold purple'
conflicted = '🏳 '
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
untracked = ''
stashed = '󰏓'
modified = ''
staged = '✓'
renamed = '⇢'
deleted = '✘'

[package]
disabled = true
[line_break]
disabled = falseformat = """
[╭](bold overlay1)-󱄅-\
$directory\
$git_branch\
$git_status\
$kubernetes \
$time \
\n$character"""

palette = 'Catppucin'

[palettes.Catppucin]
color_fg0 = '#ebdbb2'
color_bg0 = '#3C4841'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#7aa2f7'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_red = '#cc241d'
color_yellow = '#d79921'


[character]
format ="""
[╰─$symbol](fg:overlay1) """
success_symbol = '[](fg:bold white)'
error_symbol = '[](fg:bold red)'

[directory]
format ="[](fg:#7FB7FF)[ 󰉋 ](bg:#7FB7FF fg:#1A1B26)[](fg:#7FB7FF bg:#B4BEFE)[ $path ](bg:#B4BEFE fg:#151520)[](fg:#B4BEFE)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_status]
style = "fg:color_orange"
format = '([$all_status]($style))'

[time]
disabled = false
time_format = "%I.%M %p"
style = "fg:color_blue"
format = '[|]($style)[󱑒 $time]($style)'

[kubernetes]
disabled = false
style = "fg:color_yellow"
format = '( | [$context]($style)( in [$namespace]($style)))'
